### ISSUE TITLE
Migration from sme8

### ISSUE THREAD

**Issue by DavidePrincipi** [NethServer/dev#5196]
Fix the migration scripts by adapting them to ns7 and the new multi-domain/account provider feature.

**Tasks/packages to fix**

- [x] nethserver-base
- [x] nethserver-cups
- [x] nethserver-directory
- [x] nethserver-dc
- [x] nethserver-ibays
- [x] nethserver-samba
- [x] nethserver-dnsmasq
- [x] nethserver-ejabberd
- [x] ~~nethserver-faxweb2~~ (not supported anymore)
- [x] nethserver-fetchmail / getmail
- [x] nethserver-hosts
- [x] nethserver-httpd
- [x] nethserver-httpd-admin
- [x] nethserver-hylafax
- [x] nethserver-mail-common
- [x] nethserver-mail-smarthost
- [x] nethserver-mail-filter
- [x] nethserver-mail-server
- [x] nethserver-mysql
- [x] nethserver-ntp
- [x] nethserver-openssh

----

See also http://wiki.nethserver.org/doku.php?id=developer:ns7_upgrade#migration-import_modules_for_sme8

**Comment by gsanchietti** [comment]
nethserver-openssh doesn't need any modification.

**Comment by gsanchietti** [comment]
nethserver-cups doesn't need any modification.

**Comment by DavidePrincipi** [comment]
nethserver-mail-server 4c920f1d2bfda674e007384b500110ca1a7be33b 7eff700ed619db0027f6c7f07290c28023163046

**Comment by gsanchietti** [comment]
nethserver-mysql doesn't need any modification.

**Comment by DavidePrincipi** [comment]
nethserver-mail-filter should not require any modification

**Comment by DavidePrincipi** [comment]
nethserver-dc: accounts are migrated but sometimes the realm join operation fails. I need to reproduce it on a clean environment...

**Comment by DavidePrincipi** [comment]
nethserver-samba: should not require any modification

**Comment by DavidePrincipi** [comment]
nethserver-httpd: migrates mod_ssl/CipherSuite prop and ``proxypass`` DB.

**Comment by DavidePrincipi** [comment]
nethserver-base: no substantial changes

**Comment by DavidePrincipi** [comment]
nethserver-dnsmasq: removed ``dnscache`` props migration (see PR above)

**Comment by gsanchietti** [comment]
In nethserver-testing:
- nethserver-dnsmasq-1.6.3-1.3.geb8c975.ns7.noarch.rpm
- nethserver-base-3.0.17-1.6.g0619937.ns7.noarch.rpm
- nethserver-mail-server-1.10.9-1.2.g3fca14f.ns7.noarch.rpm
- nethserver-directory-3.1.3-1.3.g90f8776.ns7.noarch.rpm
- nethserver-httpd-admin-2.0.8-1.3.g93a4210.ns7.noarch.rpm

**Comment by DavidePrincipi** [comment]
In nethserver-testing:
nethserver-ntp-1.1.1-1.3.g71e5f8b.ns7.noarch.rpm

**Comment by DavidePrincipi** [comment]
Error messages from nethserver-directory:

<pre>
[INFO] Move /root/migration/home/e-smith/files/users/terzo.utente to /var/lib/nethserver/home/terzo.utente
chown: invalid option -- 'r'
Try 'chown --help' for more information.
</pre>

and

<pre>
Event: user-create admin Local Administrator
[ERROR] Changing home dir ownership failed for terzo.utente
Account creation failed: error creating a LDAP directory entry: Already exists.
Failed to create user account `admin`.
Action: /etc/e-smith/events/user-create/S04nethserver-directory-user-create FAILED: 2 [0.22867]
[NOTICE] clearing sssd cache for user admin@nethesis.it
Action: /etc/e-smith/events/user-create/S90nethserver-sssd-clear-cache SUCCESS [0.126068]
Event: user-create FAILED
</pre>

**Comment by DavidePrincipi** [comment]
Fixed.

In nethserver-testing:
nethserver-directory-3.1.3-1.5.g1e27fdd.ns7.noarch.rpm

**Comment by filippocarletti** [comment]
I found a couple of issues:
1. max shared folder name length is reduced at old value of 12
2. old ibays appear as shared folders with the Visible property not selected

```
Mar  6 14:04:24 ns7ent /etc/e-smith/events/migration-import/S20nethserver-base-migrate[16665]: /var/lib/nethserver/db/configuration: OLD maxIbayNameLength=30
Mar  6 14:04:24 ns7ent /etc/e-smith/events/migration-import/S20nethserver-base-migrate[16665]: /var/lib/nethserver/db/configuration: NEW maxIbayNameLength=12
```

**Comment by gsanchietti** [comment]
Both fixed in the following testing packages:
- nethserver-samba-2.0.4-1.3.g3f431f6.ns7.noarch.rpm
- nethserver-base-3.0.17-1.8.g778fe98.ns7.noarch.rpm

**Comment by filippocarletti** [comment]
Now `config show maxIbayNameLength` returns an empty string.
All shared folders have `SmbShareBrowseable=enabled`

**Comment by gsanchietti** [comment]
Released:
- nethserver-dnsmasq-1.6.4-1.ns7.noarch.rpm
- nethserver-base-3.0.18-1.ns7.noarch.rpm
- nethserver-mail-server-1.10.10.ns7.noarch.rpm
- nethserver-httpd-admin-2.0.9-1.ns7.noarch.rpm
- nethserver-ejabberd-1.1.4-1.ns7.noarch.rpm
- nethserver-getmail-1.0.1-1.ns7.noarch.rpm
- nethserver-ntp-1.1.2-1.ns7.noarch.rpm
- nethserver-dc-1.1.3-1.ns7.x86_64.rpm
- nethserver-directory-3.1.4-1.ns7.noarch.rpm
