### ISSUE TITLE
Upgrade from NS 6 via backup and restore

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/dev#5234]
Restore configuration and data from NethServer 6 to NethServer 7.
Also take care of  the new multi-domain/account provider feature.

**Tasks/packages to fix**

- [x] nethserver-base
- [x] nethserver-directory
- [x] nethserver-dc
- [x] nethserver-ibays
- [x] nethserver-samba
- [x] nethserver-getmail 
- [x] nethserver-httpd
- [x] nethserver-mail-common
- [x] nethserver-mail-smarthost
- [x] nethserver-mail-filter
- [x] nethserver-mail-server (import script from AD will not be developer right now)
- [x] nethserver-nexctloud
- [x] nethserver-firewall-base 
- [x] nethserver-ipsec 
- [x] nethserver-openvpn 
- [x] nethserver-iaxmodem
- [x] nethserver-nut 
- [x] nethserver-letsencrypt

See also
- http://wiki.nethserver.org/doku.php?id=developer:ns7_upgrade#restore_from_ns6
- http://community.nethserver.org/t/upgrade-paths-to-ns7/4771

**Comment by DavidePrincipi** [comment]
nethserver-directory, nethserver-samba: use cases:

1. Upgrade of systems with Samba WS/PDC role
2. Upgrade of systems with Samba ADS role

**Comment by gsanchietti** [comment]
nethserver-openvpn doesn't require any change: https://github.com/NethServer/nethserver-openvpn/commit/ad20687386f30b886d45a5b9549d17c7bb93a722

**Comment by gsanchietti** [comment]
nethserver-nut doesn't require any change: https://github.com/NethServer/nethserver-nut/commit/b8e27cdc783f35f805e7d6c0f6533c199393ae76

**Comment by gsanchietti** [comment]
nethserver-ipsec doesn't support L2TP anymore. Migration for nethserver-ipsec-tunnels is not needed.

**Comment by gsanchietti** [comment]
nethserver-letsencrypt doesn't require any change

**Comment by gsanchietti** [comment]
nethserver-iaxmodem doesn't require any change

**Comment by gsanchietti** [comment]
The FQDN of the server and the time zone are not migrated since the user is forced to enter these values during the first configuration wizard.

**Comment by gsanchietti** [comment]
nethserver-mail-smarthost doesn't require any change

**Comment by gsanchietti** [comment]
nethserver-httpd doesn't require any change

**Comment by DavidePrincipi** [comment]
In nethserver-testing:
nethserver-directory-3.1.4-1.10.g769d8b2.ns7.noarch.rpm
nethserver-dc-1.1.3-1.11.g08da35c.ns7.x86_64.rpm

TODO: ADS mode upgrade

**Comment by gsanchietti** [comment]
In nethserver-testing:
- nethserver-base-3.0.18-1.2.g044e255.ns7.noarch.rpm
- nethserver-backup-config-1.5.2-1.3.g71c68b9.ns7.noarch.rpm
- nethserver-firewall-base-3.1.6-1.4.g4edb80a.ns7.noarch.rpm
- nethserver-firewall-base-ui-3.1.6-1.4.g4edb80a.ns7.noarch.rpm
- nethserver-getmail-1.0.1-1.2.g6303b9b.ns7.noarch.rpm

**Comment by gsanchietti** [comment]
In nethserver-testing:

- nethserver-sssd-1.1.9-1.4.g67536a3.ns7.noarch.rpm
- nethserver-directory-3.1.4-1.12.ga267270.ns7.noarch.rpm
- nethserver-mail-server-1.10.10-1.2.g16fc122.ns7.noarch.rpm

**Comment by DavidePrincipi** [comment]
In nethserver-testing:
nethserver-samba-2.0.5-1.3.gc25d8ea.ns7.noarch.rpm

**Comment by gsanchietti** [comment]
In nethserver-testing:

- nethserver-directory-3.1.4-1.15.g0b45526.ns7.noarch.rpm

**Comment by DavidePrincipi** [comment]
**Test case**

Follow the documentation and check ``/var/log/messages`` for any error

http://docs.nethserver.org/en/latest/upgrade.html

**Comment by DavidePrincipi** [comment]
In nethserver-testing:
nethserver-mail-server-1.10.10-1.5.gaa47f71.ns7.noarch.rpm

----

**Test case**

After ns6 upgrade procedure, go to Email > Mailboxes > Spam message handling section.

The ``Move to "Junk" folder`` label should be actually ``Move to "junkmail" folder``, and reflect the value in config DB  ``dovecot/SpamFolder`` prop.

**Comment by gsanchietti** [comment]
In nethserver-testing:
nethserver-directory-3.1.4-1.19.gba45df5.ns7.noarch.rpm

**Comment by DavidePrincipi** [comment]
In nethserver-updates:
nethserver-ibays-3.1.0-1.ns7.noarch.rpm

**Comment by DavidePrincipi** [comment]
In nethserver-updates:
nethserver-firewall-base-3.1.7-1.ns7.noarch.rpm
nethserver-firewall-base-ui-3.1.7-1.ns7.noarch.rpm

**Comment by DavidePrincipi** [comment]
In nethserver-updates:
nethserver-mail-server-1.10.11-1.ns7.noarch.rpm

**Comment by DavidePrincipi** [comment]
In nethserver-updates:
nethserver-samba-2.0.6-1.ns7.noarch.rpm

**Comment by gsanchietti** [comment]
In nethserver-updates:
nethserver-base-3.0.19-1.ns7.noarch.rpm

**Comment by DavidePrincipi** [comment]
In nethserver-updates:
nethserver-directory-3.2.0-1.ns7.noarch.rpm

**Comment by DavidePrincipi** [comment]
In nethserver-testing:
nethserver-sssd-1.1.9-1.40.ge6a6dad.ns7.noarch.rpm
nethserver-directory-3.2.0-1.2.g6b4e21e.ns7.noarch.rpm

**Comment by DavidePrincipi** [comment]
In nethserver-testing:
nethserver-directory-3.2.0-1.6.g136b544.ns7.noarch.rpm

**Comment by gsanchietti** [comment]
In nethserver-testing:
nethserver-sssd-1.1.9-1.55.g0ed1992.ns7.noarch.rpm
nethserver-directory-3.2.0-1.8.g0ee4e5e.ns7.noarch.rpm
nethserver-dc-1.1.3-1.73.gab1e3d9.ns7.x86_64.rpm

**Comment by gsanchietti** [comment]
In nethserver-testing:
nethserver-sssd-1.1.9-1.62.g385ccb4.ns7.noarch.rpm
nethserver-ibays-3.1.0-1.2.g970178e.ns7.noarch.rpm
nethserver-dc-1.1.3-1.78.g72b97c6.ns7.x86_64.rpm

**Comment by gsanchietti** [comment]
In nethserver-testing:
nethserver-sssd-1.1.9-1.66.g1250d88.ns7.noarch.rpm
nethserver-directory-3.2.0-1.10.gaafbb73.ns7.noarch.rpm

**Comment by gsanchietti** [comment]
In nethserver-testing:
nethserver-iaxmodem-1.2.0-1.5.g88db799.ns7.noarch.rpm
nethserver-hylafax-1.2.2-1.2.gfc27f17.ns7.noarch.rpm

**Comment by DavidePrincipi** [comment]
In nethserver-testing:
nethserver-firewall-base-3.1.8-1.1.g5041da3.ns7.noarch.rpm

**Comment by gsanchietti** [comment]
In nethserver-testing:
nethserver-directory-3.2.0-1.14.gd214266.ns7.noarch.rpm

**Comment by gsanchietti** [comment]
In nethserver-testing:
nethserver-nextcloud-1.1.1-1.4.gc533336.ns7.noarch.rpm
nethserver-owncloud-2.0.0-1.1.gbe70da7.ns7.noarch.rpm

**Comment by DavidePrincipi** [comment]
In nethserver-updates:
nethserver-directory-3.2.1-1.ns7.noarch.rpm

**Comment by gsanchietti** [comment]
Released in nethserver-updates:
* nethserver-sssd-1.2.0-1.ns7.noarch.rpm
* nethserver-dc-1.2.0-1.ns7.x86_64.rpm
* nethserver-owncloud-2.0.1-1.ns7.noarch.rpm
* nethserver-nextcloud-1.1.2-1.ns7.noarch.rpm
* nethserver-firewall-base-3.2.0-1.ns7.noarch.rpm
* nethserver-firewall-base-ui-3.2.0-1.ns7.noarch.rpm
* nethserver-backup-config-1.5.4-1.ns7.noarch.rpm
* nethserver-collectd-3.0.5-1.ns7.noarch.rpm
* nethserver-hylafax-1.2.3-1.ns7.noarch.rpm
* nethserver-iaxmodem-1.2.1-1.ns7.noarch.rpm
