### ISSUE TITLE
Accounts provider guided configuration

### ISSUE THREAD

**Issue by DavidePrincipi** [NethServer/dev#5253]
The "Accounts provider" UI page must guide the sysadmin through some configuration steps to obtain a fully functional system. Add the following enhancements:

**Active directory**

- [x] Specify custom Realm and NetBIOS values
- [x] Join as AD member, 
- [x] LDAP client auth kerberos/simple bind
- [x] Install/uninstall local AD provider (#5252)
- [x] Upgrade nsdc to new Samba release (#5251)
- [x] Check the given nsdc IP address is free
- [x] Remove bridge creation checkbox

**LDAP**

- [x] Install/uninstall local LDAP provider (#5252)
- [x] Upgrade ns6 directory to AD
- [x] Bind remote LDAP, auth method choice: anonymous/simple bind

**See also**

http://community.nethserver.org/t/accounts-provider-service-pack-1/6351

**Comment by DavidePrincipi** [comment]
In nethserver-testing:
nethserver-sssd-1.1.9-1.32.g28f0ee9.ns7.noarch.rpm
nethserver-dc-1.1.3-1.54.g22dc4c6.ns7.x86_64.rpm
nethserver-samba-2.0.5-1.5.g8d6307a.ns7.noarch.rpm

And:
nethserver-directory-3.1.4-1.24.gf82c490.ns7.noarch.rpm

**Test case**

Test all accounts provider scenario combinations: remote/local, AD/LDAP.

**Comment by DavidePrincipi** [comment]
Open issues:

- [ ] the nsdc service fails to start after reboot, or restart
- [ ] the remote LDAP probe procedure does not validate server/port combination - it always fall back to default values which do not make sense

**Comment by DavidePrincipi** [comment]
In nethserver-testing:
nethserver-dc-1.1.3-1.56.g50c99ca.ns7.x86_64.rpm

**Comment by gsanchietti** [comment]
In nethserver-testing:
nethserver-sssd-1.1.9-1.35.g01d801e.ns7.noarch.rpm

**Comment by gsanchietti** [comment]
In nethserver-testing:
nethserver-sssd-1.1.9-1.37.g1631250.ns7.noarch.rpm

**Comment by DavidePrincipi** [comment]
In nethserver-updates
nethserver-samba-2.0.6-1.ns7.noarch.rpm

**Comment by DavidePrincipi** [comment]
In nethserver-updates:
nethserver-directory-3.2.0-1.ns7.noarch.rpm

**Comment by gsanchietti** [comment]
Tested:
- nethserver-dc install/uninstall
- nethserver-directory install/uninstall
- bind/unbind remote ldap
- bind/unbind remote AD
- user list pagination
- upgrade nsdc container

**Comment by roswitina** [comment]
yum install --enablerepo=nethforge-testing nethserver-directory
Loaded plugins: changelog, fastestmirror, nethserver_events
Loading mirror speeds from cached hostfile
 * base: gd.tuwien.ac.at
 * epel: ftp.upjs.sk
 * extras: gd.tuwien.ac.at
 * nethforge: mirror.framassa.org
 * nethserver-base: mirror.framassa.org
 * nethserver-updates: mirror.framassa.org
 * updates: gd.tuwien.ac.at
Resolving Dependencies
--> Running transaction check
---> Package nethserver-directory.noarch 0:3.2.0-1.2.g6b4e21e.ns7 will be installed
--> Processing Conflict: nethserver-dc-1.1.3-1.56.g50c99ca.ns7.x86_64 conflicts nethserver-directory
--> Finished Dependency Resolution
Error: nethserver-dc conflicts with nethserver-directory-3.2.0-1.2.g6b4e21e.ns7.noarch
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest

What am I doing wrong?

**Comment by gsanchietti** [comment]
> What am I doing wrong?

You can't install nethserver-directory if nethserver-dc is installed (and vice-versa).
If you want to try the features which replace one account provider with another one, you must use the web interface (or manually call the related events).

**Comment by DavidePrincipi** [comment]
In nethserver-testing:
nethserver-sssd-1.1.9-1.52.g74c6b1c.ns7.noarch.rpm

**Comment by DavidePrincipi** [comment]
In nethserver-testing:
nethserver-sssd-1.1.9-1.62.g385ccb4.ns7.noarch.rpm
nethserver-dc-1.1.3-1.78.g72b97c6.ns7.x86_64.rpm

**Comment by DavidePrincipi** [comment]
In nethserver-updates:
nethserver-directory-3.2.1-1.ns7.noarch.rpm

**Comment by gsanchietti** [comment]
Released in nethserver-updates:
* nethserver-sssd-1.2.0-1.ns7.noarch.rpm
* nethserver-dc-1.2.0-1.ns7.x86_64.rpm
