### ISSUE TITLE
Implement clients for NethServer Subscriptions

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/dev#5425]
Enterprise Support Subscriptions are paid plans for NethServer. More info at https://community.nethserver.org/t/enterprise-support-subscriptions-feedback/8337.

The client is composed by 3 main parts:

- nethserver-subscription: handle the system registration and configure YUM repositories
- nethserver-inventory: generates a machine inventory and send it to the remote server
- nethserver-alerts: monitor the machine and sent alerts to the remote server

**Comment by nethbot** [comment]
in `7.4.1708/testing`:
- [nethserver-alerts-1.1.3-1.13.g2904718.ns7.noarch.rpm](http://packages.nethserver.org/nethserver/7.4.1708/testing/x86_64/Packages/nethserver-alerts-1.1.3-1.13.g2904718.ns7.noarch.rpm)

**Comment by nethbot** [comment]
in `7.4.1708/testing`:
- [nethserver-inventory-2.0.8-1.16.g42401f1.ns7.noarch.rpm](http://packages.nethserver.org/nethserver/7.4.1708/testing/x86_64/Packages/nethserver-inventory-2.0.8-1.16.g42401f1.ns7.noarch.rpm)

**Comment by nethbot** [comment]
in `7.4.1708/testing`:
- [nethserver-alerts-1.1.3-1.14.g6b724bc.ns7.noarch.rpm](http://packages.nethserver.org/nethserver/7.4.1708/testing/x86_64/Packages/nethserver-alerts-1.1.3-1.14.g6b724bc.ns7.noarch.rpm)

**Comment by nethbot** [comment]
in `7.4.1708/testing`:
- [nethserver-inventory-2.0.8-1.18.g311652c.ns7.noarch.rpm](http://packages.nethserver.org/nethserver/7.4.1708/testing/x86_64/Packages/nethserver-inventory-2.0.8-1.18.g311652c.ns7.noarch.rpm)

**Comment by nethbot** [comment]
in `7.4.1708/testing`:
- [nethserver-subscription-0.0.1-1.12.g43b95c0.ns7.noarch.rpm](http://packages.nethserver.org/nethserver/7.4.1708/testing/x86_64/Packages/nethserver-subscription-0.0.1-1.12.g43b95c0.ns7.noarch.rpm)
- [nethserver-subscription-ui-0.0.1-1.12.g43b95c0.ns7.noarch.rpm](http://packages.nethserver.org/nethserver/7.4.1708/testing/x86_64/Packages/nethserver-subscription-ui-0.0.1-1.12.g43b95c0.ns7.noarch.rpm)

**Comment by nethbot** [comment]
in `7.4.1708/testing`:
- [nethserver-subscription-ui-0.0.1-1.13.gdf3154b.ns7.noarch.rpm](http://packages.nethserver.org/nethserver/7.4.1708/testing/x86_64/Packages/nethserver-subscription-ui-0.0.1-1.13.gdf3154b.ns7.noarch.rpm)
- [nethserver-subscription-0.0.1-1.13.gdf3154b.ns7.noarch.rpm](http://packages.nethserver.org/nethserver/7.4.1708/testing/x86_64/Packages/nethserver-subscription-0.0.1-1.13.gdf3154b.ns7.noarch.rpm)

**Comment by nethbot** [comment]
in `7.4.1708/testing`:
- [nethserver-subscription-0.0.1-1.17.g12445be.ns7.noarch.rpm](http://packages.nethserver.org/nethserver/7.4.1708/testing/x86_64/Packages/nethserver-subscription-0.0.1-1.17.g12445be.ns7.noarch.rpm)
- [nethserver-subscription-ui-0.0.1-1.17.g12445be.ns7.noarch.rpm](http://packages.nethserver.org/nethserver/7.4.1708/testing/x86_64/Packages/nethserver-subscription-ui-0.0.1-1.17.g12445be.ns7.noarch.rpm)

**Comment by nethbot** [comment]
in `7.4.1708/testing`:
- [nethserver-inventory-2.0.8-1.19.g641ae05.ns7.noarch.rpm](http://packages.nethserver.org/nethserver/7.4.1708/testing/x86_64/Packages/nethserver-inventory-2.0.8-1.19.g641ae05.ns7.noarch.rpm)

**Comment by nethbot** [comment]
in `7.4.1708/testing`:
- [nethserver-subscription-0.0.1-1.18.g6c55129.ns7.noarch.rpm](http://packages.nethserver.org/nethserver/7.4.1708/testing/x86_64/Packages/nethserver-subscription-0.0.1-1.18.g6c55129.ns7.noarch.rpm)
- [nethserver-subscription-ui-0.0.1-1.18.g6c55129.ns7.noarch.rpm](http://packages.nethserver.org/nethserver/7.4.1708/testing/x86_64/Packages/nethserver-subscription-ui-0.0.1-1.18.g6c55129.ns7.noarch.rpm)

**Comment by nethbot** [comment]
in `7.4.1708/testing`:
- [nethserver-subscription-0.0.1-1.20.g66cfa08.ns7.noarch.rpm](http://packages.nethserver.org/nethserver/7.4.1708/testing/x86_64/Packages/nethserver-subscription-0.0.1-1.20.g66cfa08.ns7.noarch.rpm)
- [nethserver-subscription-ui-0.0.1-1.20.g66cfa08.ns7.noarch.rpm](http://packages.nethserver.org/nethserver/7.4.1708/testing/x86_64/Packages/nethserver-subscription-ui-0.0.1-1.20.g66cfa08.ns7.noarch.rpm)

**Comment by nethbot** [comment]
in `7.4.1708/testing`:
- [nethserver-inventory-2.0.8-1.21.ga29caf5.ns7.noarch.rpm](http://packages.nethserver.org/nethserver/7.4.1708/testing/x86_64/Packages/nethserver-inventory-2.0.8-1.21.ga29caf5.ns7.noarch.rpm)

**Comment by nethbot** [comment]
in `7.4.1708/testing`:
- [nethserver-alerts-1.1.3-1.17.gc8e1945.ns7.noarch.rpm](http://packages.nethserver.org/nethserver/7.4.1708/testing/x86_64/Packages/nethserver-alerts-1.1.3-1.17.gc8e1945.ns7.noarch.rpm)

**Comment by nethbot** [comment]
in `7.4.1708/testing`:
- [nethserver-subscription-ui-0.0.1-1.21.g10422f6.ns7.noarch.rpm](http://packages.nethserver.org/nethserver/7.4.1708/testing/x86_64/Packages/nethserver-subscription-ui-0.0.1-1.21.g10422f6.ns7.noarch.rpm)
- [nethserver-subscription-0.0.1-1.21.g10422f6.ns7.noarch.rpm](http://packages.nethserver.org/nethserver/7.4.1708/testing/x86_64/Packages/nethserver-subscription-0.0.1-1.21.g10422f6.ns7.noarch.rpm)

**Comment by nethbot** [comment]
in `7.4.1708/testing`:
- [nethserver-subscription-0.0.1-1.28.gd26f6e1.ns7.noarch.rpm](http://packages.nethserver.org/nethserver/7.4.1708/testing/x86_64/Packages/nethserver-subscription-0.0.1-1.28.gd26f6e1.ns7.noarch.rpm)
- [nethserver-subscription-ui-0.0.1-1.28.gd26f6e1.ns7.noarch.rpm](http://packages.nethserver.org/nethserver/7.4.1708/testing/x86_64/Packages/nethserver-subscription-ui-0.0.1-1.28.gd26f6e1.ns7.noarch.rpm)

**Comment by nethbot** [comment]
in `7.4.1708/testing`:
- [nethserver-subscription-0.0.1-1.32.g1281d10.ns7.noarch.rpm](http://packages.nethserver.org/nethserver/7.4.1708/testing/x86_64/Packages/nethserver-subscription-0.0.1-1.32.g1281d10.ns7.noarch.rpm)
- [nethserver-subscription-ui-0.0.1-1.32.g1281d10.ns7.noarch.rpm](http://packages.nethserver.org/nethserver/7.4.1708/testing/x86_64/Packages/nethserver-subscription-ui-0.0.1-1.32.g1281d10.ns7.noarch.rpm)

**Comment by nethbot** [comment]
in `7.4.1708/testing`:
- [nethserver-subscription-ui-0.0.1-1.33.g919912e.ns7.noarch.rpm](http://packages.nethserver.org/nethserver/7.4.1708/testing/x86_64/Packages/nethserver-subscription-ui-0.0.1-1.33.g919912e.ns7.noarch.rpm)
- [nethserver-subscription-0.0.1-1.33.g919912e.ns7.noarch.rpm](http://packages.nethserver.org/nethserver/7.4.1708/testing/x86_64/Packages/nethserver-subscription-0.0.1-1.33.g919912e.ns7.noarch.rpm)

**Comment by nethbot** [comment]
in `7.4.1708/testing`:
- [nethserver-alerts-1.1.3-1.18.gd503e4d.ns7.noarch.rpm](http://packages.nethserver.org/nethserver/7.4.1708/testing/x86_64/Packages/nethserver-alerts-1.1.3-1.18.gd503e4d.ns7.noarch.rpm)

**Comment by nethbot** [comment]
in `7.4.1708/testing`:
- [nethserver-subscription-ui-0.0.1-1.34.g52b5c14.ns7.noarch.rpm](http://packages.nethserver.org/nethserver/7.4.1708/testing/x86_64/Packages/nethserver-subscription-ui-0.0.1-1.34.g52b5c14.ns7.noarch.rpm)
- [nethserver-subscription-0.0.1-1.34.g52b5c14.ns7.noarch.rpm](http://packages.nethserver.org/nethserver/7.4.1708/testing/x86_64/Packages/nethserver-subscription-0.0.1-1.34.g52b5c14.ns7.noarch.rpm)

**Comment by nethbot** [comment]
in `7.4.1708/testing`:
- [nethserver-alerts-1.1.3-1.19.g7677def.ns7.noarch.rpm](http://packages.nethserver.org/nethserver/7.4.1708/testing/x86_64/Packages/nethserver-alerts-1.1.3-1.19.g7677def.ns7.noarch.rpm)

**Comment by nethbot** [comment]
in `7.4.1708/testing`:
- [nethserver-inventory-2.0.8-1.22.ga1d30c8.ns7.noarch.rpm](http://packages.nethserver.org/nethserver/7.4.1708/testing/x86_64/Packages/nethserver-inventory-2.0.8-1.22.ga1d30c8.ns7.noarch.rpm)

**Comment by nethbot** [comment]
in `7.4.1708/testing`:
- [nethserver-yum-cron-0.1.7-1.6.gc79a427.ns7.noarch.rpm](http://packages.nethserver.org/nethserver/7.4.1708/testing/x86_64/Packages/nethserver-yum-cron-0.1.7-1.6.gc79a427.ns7.noarch.rpm)

**Comment by nethbot** [comment]
in `7.4.1708/testing`:
- [nethserver-subscription-ui-0.0.1-1.35.g8f7903a.ns7.noarch.rpm](http://packages.nethserver.org/nethserver/7.4.1708/testing/x86_64/Packages/nethserver-subscription-ui-0.0.1-1.35.g8f7903a.ns7.noarch.rpm)
- [nethserver-subscription-0.0.1-1.35.g8f7903a.ns7.noarch.rpm](http://packages.nethserver.org/nethserver/7.4.1708/testing/x86_64/Packages/nethserver-subscription-0.0.1-1.35.g8f7903a.ns7.noarch.rpm)

**Comment by nethbot** [comment]
in `7.4.1708/testing`:
- [nethserver-p3scan-1.1.3-1.1.g59c3c3f.ns7.noarch.rpm](http://packages.nethserver.org/nethserver/7.4.1708/testing/x86_64/Packages/nethserver-p3scan-1.1.3-1.1.g59c3c3f.ns7.noarch.rpm)

**Comment by nethbot** [comment]
in `7.4.1708/testing`:
- [nethserver-mail2-getmail-2.0.0-1.1.g3f9c6fc.ns7.noarch.rpm](http://packages.nethserver.org/nethserver/7.4.1708/testing/x86_64/Packages/nethserver-mail2-getmail-2.0.0-1.1.g3f9c6fc.ns7.noarch.rpm)
- [nethserver-mail2-common-2.0.0-1.1.g3f9c6fc.ns7.noarch.rpm](http://packages.nethserver.org/nethserver/7.4.1708/testing/x86_64/Packages/nethserver-mail2-common-2.0.0-1.1.g3f9c6fc.ns7.noarch.rpm)
- [nethserver-mail2-filter-2.0.0-1.1.g3f9c6fc.ns7.noarch.rpm](http://packages.nethserver.org/nethserver/7.4.1708/testing/x86_64/Packages/nethserver-mail2-filter-2.0.0-1.1.g3f9c6fc.ns7.noarch.rpm)
- [nethserver-mail2-server-2.0.0-1.1.g3f9c6fc.ns7.noarch.rpm](http://packages.nethserver.org/nethserver/7.4.1708/testing/x86_64/Packages/nethserver-mail2-server-2.0.0-1.1.g3f9c6fc.ns7.noarch.rpm)
- [nethserver-mail2-p3scan-2.0.0-1.1.g3f9c6fc.ns7.noarch.rpm](http://packages.nethserver.org/nethserver/7.4.1708/testing/x86_64/Packages/nethserver-mail2-p3scan-2.0.0-1.1.g3f9c6fc.ns7.noarch.rpm)
- [nethserver-mail2-ipaccess-2.0.0-1.1.g3f9c6fc.ns7.noarch.rpm](http://packages.nethserver.org/nethserver/7.4.1708/testing/x86_64/Packages/nethserver-mail2-ipaccess-2.0.0-1.1.g3f9c6fc.ns7.noarch.rpm)

**Comment by nethbot** [comment]
in `7.4.1708/testing`:
- [nethserver-subscription-0.0.1-1.36.g79643e8.ns7.noarch.rpm](http://packages.nethserver.org/nethserver/7.4.1708/testing/x86_64/Packages/nethserver-subscription-0.0.1-1.36.g79643e8.ns7.noarch.rpm)
- [nethserver-subscription-ui-0.0.1-1.36.g79643e8.ns7.noarch.rpm](http://packages.nethserver.org/nethserver/7.4.1708/testing/x86_64/Packages/nethserver-subscription-ui-0.0.1-1.36.g79643e8.ns7.noarch.rpm)

**Comment by nethbot** [comment]
in `7.4.1708/testing`:
- [nethserver-lang-el-1.2.6-1.1.gcf6e74c.ns7.noarch.rpm](http://packages.nethserver.org/nethserver/7.4.1708/testing/x86_64/Packages/nethserver-lang-el-1.2.6-1.1.gcf6e74c.ns7.noarch.rpm)
- [nethserver-lang-nl-1.2.6-1.1.gcf6e74c.ns7.noarch.rpm](http://packages.nethserver.org/nethserver/7.4.1708/testing/x86_64/Packages/nethserver-lang-nl-1.2.6-1.1.gcf6e74c.ns7.noarch.rpm)
- [nethserver-lang-tr-1.2.6-1.1.gcf6e74c.ns7.noarch.rpm](http://packages.nethserver.org/nethserver/7.4.1708/testing/x86_64/Packages/nethserver-lang-tr-1.2.6-1.1.gcf6e74c.ns7.noarch.rpm)
- [nethserver-lang-hu-1.2.6-1.1.gcf6e74c.ns7.noarch.rpm](http://packages.nethserver.org/nethserver/7.4.1708/testing/x86_64/Packages/nethserver-lang-hu-1.2.6-1.1.gcf6e74c.ns7.noarch.rpm)
- [nethserver-lang-ru-1.2.6-1.1.gcf6e74c.ns7.noarch.rpm](http://packages.nethserver.org/nethserver/7.4.1708/testing/x86_64/Packages/nethserver-lang-ru-1.2.6-1.1.gcf6e74c.ns7.noarch.rpm)
- [nethserver-lang-es-1.2.6-1.1.gcf6e74c.ns7.noarch.rpm](http://packages.nethserver.org/nethserver/7.4.1708/testing/x86_64/Packages/nethserver-lang-es-1.2.6-1.1.gcf6e74c.ns7.noarch.rpm)
- [nethserver-lang-sr-1.2.6-1.1.gcf6e74c.ns7.noarch.rpm](http://packages.nethserver.org/nethserver/7.4.1708/testing/x86_64/Packages/nethserver-lang-sr-1.2.6-1.1.gcf6e74c.ns7.noarch.rpm)
- [nethserver-lang-pt-1.2.6-1.1.gcf6e74c.ns7.noarch.rpm](http://packages.nethserver.org/nethserver/7.4.1708/testing/x86_64/Packages/nethserver-lang-pt-1.2.6-1.1.gcf6e74c.ns7.noarch.rpm)
- [nethserver-lang-sv-1.2.6-1.1.gcf6e74c.ns7.noarch.rpm](http://packages.nethserver.org/nethserver/7.4.1708/testing/x86_64/Packages/nethserver-lang-sv-1.2.6-1.1.gcf6e74c.ns7.noarch.rpm)
- [nethserver-lang-cs-1.2.6-1.1.gcf6e74c.ns7.noarch.rpm](http://packages.nethserver.org/nethserver/7.4.1708/testing/x86_64/Packages/nethserver-lang-cs-1.2.6-1.1.gcf6e74c.ns7.noarch.rpm)
- [nethserver-lang-en-1.2.6-1.1.gcf6e74c.ns7.noarch.rpm](http://packages.nethserver.org/nethserver/7.4.1708/testing/x86_64/Packages/nethserver-lang-en-1.2.6-1.1.gcf6e74c.ns7.noarch.rpm)
- [nethserver-lang-fr-1.2.6-1.1.gcf6e74c.ns7.noarch.rpm](http://packages.nethserver.org/nethserver/7.4.1708/testing/x86_64/Packages/nethserver-lang-fr-1.2.6-1.1.gcf6e74c.ns7.noarch.rpm)
- [nethserver-lang-de-1.2.6-1.1.gcf6e74c.ns7.noarch.rpm](http://packages.nethserver.org/nethserver/7.4.1708/testing/x86_64/Packages/nethserver-lang-de-1.2.6-1.1.gcf6e74c.ns7.noarch.rpm)
- [nethserver-lang-ro-1.2.6-1.1.gcf6e74c.ns7.noarch.rpm](http://packages.nethserver.org/nethserver/7.4.1708/testing/x86_64/Packages/nethserver-lang-ro-1.2.6-1.1.gcf6e74c.ns7.noarch.rpm)
- [nethserver-lang-it-1.2.6-1.1.gcf6e74c.ns7.noarch.rpm](http://packages.nethserver.org/nethserver/7.4.1708/testing/x86_64/Packages/nethserver-lang-it-1.2.6-1.1.gcf6e74c.ns7.noarch.rpm)

**Comment by nethbot** [comment]
in `7.4.1708/testing`:
- [nethserver-yum-cron-0.1.7-1.7.g6c130dc.ns7.noarch.rpm](http://packages.nethserver.org/nethserver/7.4.1708/testing/x86_64/Packages/nethserver-yum-cron-0.1.7-1.7.g6c130dc.ns7.noarch.rpm)

**Comment by DavidePrincipi** [comment]
**TODO**

- [ ] split alerts UI for Enterprise version

**Comment by nethbot** [comment]
in `7.4.1708/testing`:
- [nethserver-subscription-ui-3.0.0-0.1.55.g0713903.ns7.noarch.rpm](http://packages.nethserver.org/nethserver/7.4.1708/testing/x86_64/Packages/nethserver-subscription-ui-3.0.0-0.1.55.g0713903.ns7.noarch.rpm)
- [nethserver-subscription-3.0.0-0.1.55.g0713903.ns7.noarch.rpm](http://packages.nethserver.org/nethserver/7.4.1708/testing/x86_64/Packages/nethserver-subscription-3.0.0-0.1.55.g0713903.ns7.noarch.rpm)

**Comment by nethbot** [comment]
in `7.4.1708/testing`:
- [nethserver-subscription-ui-3.0.0-0.1.57.g50f9f48.ns7.noarch.rpm](http://packages.nethserver.org/nethserver/7.4.1708/testing/x86_64/Packages/nethserver-subscription-ui-3.0.0-0.1.57.g50f9f48.ns7.noarch.rpm)
- [nethserver-subscription-3.0.0-0.1.57.g50f9f48.ns7.noarch.rpm](http://packages.nethserver.org/nethserver/7.4.1708/testing/x86_64/Packages/nethserver-subscription-3.0.0-0.1.57.g50f9f48.ns7.noarch.rpm)

**Comment by nethbot** [comment]
in `7.4.1708/testing`:
- [nethserver-subscription-3.0.0-0.1.58.g7d3d397.ns7.noarch.rpm](http://packages.nethserver.org/nethserver/7.4.1708/testing/x86_64/Packages/nethserver-subscription-3.0.0-0.1.58.g7d3d397.ns7.noarch.rpm)
- [nethserver-subscription-ui-3.0.0-0.1.58.g7d3d397.ns7.noarch.rpm](http://packages.nethserver.org/nethserver/7.4.1708/testing/x86_64/Packages/nethserver-subscription-ui-3.0.0-0.1.58.g7d3d397.ns7.noarch.rpm)

**Comment by nethbot** [comment]
in `7.4.1708/testing`:
- [nethserver-subscription-ui-3.0.0-0.1.65.g34d0bdb.ns7.noarch.rpm](http://packages.nethserver.org/nethserver/7.4.1708/testing/x86_64/Packages/nethserver-subscription-ui-3.0.0-0.1.65.g34d0bdb.ns7.noarch.rpm)
- [nethserver-subscription-3.0.0-0.1.65.g34d0bdb.ns7.noarch.rpm](http://packages.nethserver.org/nethserver/7.4.1708/testing/x86_64/Packages/nethserver-subscription-3.0.0-0.1.65.g34d0bdb.ns7.noarch.rpm)

**Comment by nethbot** [comment]
in `7.4.1708/testing`:
- [nethserver-subscription-ui-3.0.0-0.1.66.ge8de85a.ns7.noarch.rpm](http://packages.nethserver.org/nethserver/7.4.1708/testing/x86_64/Packages/nethserver-subscription-ui-3.0.0-0.1.66.ge8de85a.ns7.noarch.rpm)
- [nethserver-subscription-3.0.0-0.1.66.ge8de85a.ns7.noarch.rpm](http://packages.nethserver.org/nethserver/7.4.1708/testing/x86_64/Packages/nethserver-subscription-3.0.0-0.1.66.ge8de85a.ns7.noarch.rpm)

**Comment by DavidePrincipi** [comment]
**Test case**

- [x] backup/restore on NethServer 7.4 with no nethserver-subscription  (relies on community repos)
- [ ] backup/restore on NethServer 7.4 with nethserver-subscription (relies on sb repos)
- [ ] install nethserver-subscription on 7.4

**Comment by nethbot** [comment]
in `7.4.1708/testing`:
- [nethserver-subscription-ui-3.0.0-0.1.67.g6596cb6.ns7.noarch.rpm](http://packages.nethserver.org/nethserver/7.4.1708/testing/x86_64/Packages/nethserver-subscription-ui-3.0.0-0.1.67.g6596cb6.ns7.noarch.rpm)
- [nethserver-subscription-3.0.0-0.1.67.g6596cb6.ns7.noarch.rpm](http://packages.nethserver.org/nethserver/7.4.1708/testing/x86_64/Packages/nethserver-subscription-3.0.0-0.1.67.g6596cb6.ns7.noarch.rpm)

**Comment by nethbot** [comment]
in `7.4.1708/testing`:
- [nethserver-subscription-3.0.0-0.1.69.g9f8cad5.ns7.noarch.rpm](http://packages.nethserver.org/nethserver/7.4.1708/testing/x86_64/Packages/nethserver-subscription-3.0.0-0.1.69.g9f8cad5.ns7.noarch.rpm)
- [nethserver-subscription-ui-3.0.0-0.1.69.g9f8cad5.ns7.noarch.rpm](http://packages.nethserver.org/nethserver/7.4.1708/testing/x86_64/Packages/nethserver-subscription-ui-3.0.0-0.1.69.g9f8cad5.ns7.noarch.rpm)

**Comment by nethbot** [comment]
in `7.4.1708/testing`:
- [nethserver-subscription-3.0.0-0.1.70.g3e8d1f7.ns7.noarch.rpm](http://packages.nethserver.org/nethserver/7.4.1708/testing/x86_64/Packages/nethserver-subscription-3.0.0-0.1.70.g3e8d1f7.ns7.noarch.rpm)
- [nethserver-subscription-ui-3.0.0-0.1.70.g3e8d1f7.ns7.noarch.rpm](http://packages.nethserver.org/nethserver/7.4.1708/testing/x86_64/Packages/nethserver-subscription-ui-3.0.0-0.1.70.g3e8d1f7.ns7.noarch.rpm)

**Comment by nethbot** [comment]
in `7.4.1708/testing`:
- [nethserver-lang-it-1.2.6-1.2.g1336c5c.ns7.noarch.rpm](http://packages.nethserver.org/nethserver/7.4.1708/testing/x86_64/Packages/nethserver-lang-it-1.2.6-1.2.g1336c5c.ns7.noarch.rpm)
- [nethserver-lang-ru-1.2.6-1.2.g1336c5c.ns7.noarch.rpm](http://packages.nethserver.org/nethserver/7.4.1708/testing/x86_64/Packages/nethserver-lang-ru-1.2.6-1.2.g1336c5c.ns7.noarch.rpm)
- [nethserver-lang-en-1.2.6-1.2.g1336c5c.ns7.noarch.rpm](http://packages.nethserver.org/nethserver/7.4.1708/testing/x86_64/Packages/nethserver-lang-en-1.2.6-1.2.g1336c5c.ns7.noarch.rpm)
- [nethserver-lang-el-1.2.6-1.2.g1336c5c.ns7.noarch.rpm](http://packages.nethserver.org/nethserver/7.4.1708/testing/x86_64/Packages/nethserver-lang-el-1.2.6-1.2.g1336c5c.ns7.noarch.rpm)
- [nethserver-lang-cs-1.2.6-1.2.g1336c5c.ns7.noarch.rpm](http://packages.nethserver.org/nethserver/7.4.1708/testing/x86_64/Packages/nethserver-lang-cs-1.2.6-1.2.g1336c5c.ns7.noarch.rpm)
- [nethserver-lang-hu-1.2.6-1.2.g1336c5c.ns7.noarch.rpm](http://packages.nethserver.org/nethserver/7.4.1708/testing/x86_64/Packages/nethserver-lang-hu-1.2.6-1.2.g1336c5c.ns7.noarch.rpm)
- [nethserver-lang-de-1.2.6-1.2.g1336c5c.ns7.noarch.rpm](http://packages.nethserver.org/nethserver/7.4.1708/testing/x86_64/Packages/nethserver-lang-de-1.2.6-1.2.g1336c5c.ns7.noarch.rpm)
- [nethserver-lang-fr-1.2.6-1.2.g1336c5c.ns7.noarch.rpm](http://packages.nethserver.org/nethserver/7.4.1708/testing/x86_64/Packages/nethserver-lang-fr-1.2.6-1.2.g1336c5c.ns7.noarch.rpm)
- [nethserver-lang-sr-1.2.6-1.2.g1336c5c.ns7.noarch.rpm](http://packages.nethserver.org/nethserver/7.4.1708/testing/x86_64/Packages/nethserver-lang-sr-1.2.6-1.2.g1336c5c.ns7.noarch.rpm)
- [nethserver-lang-nl-1.2.6-1.2.g1336c5c.ns7.noarch.rpm](http://packages.nethserver.org/nethserver/7.4.1708/testing/x86_64/Packages/nethserver-lang-nl-1.2.6-1.2.g1336c5c.ns7.noarch.rpm)
- [nethserver-lang-ro-1.2.6-1.2.g1336c5c.ns7.noarch.rpm](http://packages.nethserver.org/nethserver/7.4.1708/testing/x86_64/Packages/nethserver-lang-ro-1.2.6-1.2.g1336c5c.ns7.noarch.rpm)
- [nethserver-lang-es-1.2.6-1.2.g1336c5c.ns7.noarch.rpm](http://packages.nethserver.org/nethserver/7.4.1708/testing/x86_64/Packages/nethserver-lang-es-1.2.6-1.2.g1336c5c.ns7.noarch.rpm)
- [nethserver-lang-tr-1.2.6-1.2.g1336c5c.ns7.noarch.rpm](http://packages.nethserver.org/nethserver/7.4.1708/testing/x86_64/Packages/nethserver-lang-tr-1.2.6-1.2.g1336c5c.ns7.noarch.rpm)
- [nethserver-lang-sv-1.2.6-1.2.g1336c5c.ns7.noarch.rpm](http://packages.nethserver.org/nethserver/7.4.1708/testing/x86_64/Packages/nethserver-lang-sv-1.2.6-1.2.g1336c5c.ns7.noarch.rpm)
- [nethserver-lang-pt-1.2.6-1.2.g1336c5c.ns7.noarch.rpm](http://packages.nethserver.org/nethserver/7.4.1708/testing/x86_64/Packages/nethserver-lang-pt-1.2.6-1.2.g1336c5c.ns7.noarch.rpm)

**Comment by nethbot** [comment]
in `7.4.1708/testing`:
- [nethserver-subscription-ui-3.0.0-0.1.74.gf32331f.ns7.noarch.rpm](http://packages.nethserver.org/nethserver/7.4.1708/testing/x86_64/Packages/nethserver-subscription-ui-3.0.0-0.1.74.gf32331f.ns7.noarch.rpm)
- [nethserver-subscription-3.0.0-0.1.74.gf32331f.ns7.noarch.rpm](http://packages.nethserver.org/nethserver/7.4.1708/testing/x86_64/Packages/nethserver-subscription-3.0.0-0.1.74.gf32331f.ns7.noarch.rpm)

**Comment by nethbot** [comment]
in `7.4.1708/testing`:
- [nethserver-yum-cron-0.1.7-1.11.gb4e5137.ns7.noarch.rpm](http://packages.nethserver.org/nethserver/7.4.1708/testing/x86_64/Packages/nethserver-yum-cron-0.1.7-1.11.gb4e5137.ns7.noarch.rpm)

**Comment by nethbot** [comment]
in `7.4.1708/testing`:
- [nethserver-subscription-ui-3.0.0-0.1.76.gcb2beee.ns7.noarch.rpm](http://packages.nethserver.org/nethserver/7.4.1708/testing/x86_64/Packages/nethserver-subscription-ui-3.0.0-0.1.76.gcb2beee.ns7.noarch.rpm)
- [nethserver-subscription-3.0.0-0.1.76.gcb2beee.ns7.noarch.rpm](http://packages.nethserver.org/nethserver/7.4.1708/testing/x86_64/Packages/nethserver-subscription-3.0.0-0.1.76.gcb2beee.ns7.noarch.rpm)

**Comment by nethbot** [comment]
in `7.4.1708/testing`:
- [nethserver-subscription-3.0.0-0.1.77.g93b7158.ns7.noarch.rpm](http://packages.nethserver.org/nethserver/7.4.1708/testing/x86_64/Packages/nethserver-subscription-3.0.0-0.1.77.g93b7158.ns7.noarch.rpm)
- [nethserver-subscription-ui-3.0.0-0.1.77.g93b7158.ns7.noarch.rpm](http://packages.nethserver.org/nethserver/7.4.1708/testing/x86_64/Packages/nethserver-subscription-ui-3.0.0-0.1.77.g93b7158.ns7.noarch.rpm)

**Comment by nethbot** [comment]
in `7.4.1708/updates`:
- [nethserver-yum-cron-1.0.0-1.ns7.noarch.rpm](http://packages.nethserver.org/nethserver/7.4.1708/updates/x86_64/Packages/nethserver-yum-cron-1.0.0-1.ns7.noarch.rpm)

**Comment by nethbot** [comment]
in `7.4.1708/updates`:
- [nethserver-subscription-3.0.0-1.ns7.noarch.rpm](http://packages.nethserver.org/nethserver/7.4.1708/updates/x86_64/Packages/nethserver-subscription-3.0.0-1.ns7.noarch.rpm)
- [nethserver-subscription-ui-3.0.0-1.ns7.noarch.rpm](http://packages.nethserver.org/nethserver/7.4.1708/updates/x86_64/Packages/nethserver-subscription-ui-3.0.0-1.ns7.noarch.rpm)
