### ISSUE TITLE
Nextcloud: upgrade to v13 & optimizations

### ISSUE THREAD

**Issue by alepolidori** [NethServer/dev#5427]
**Description**

_Ugrade_ nextcloud to version [13.0.0](https://download.nextcloud.com/server/releases/nextcloud-13.0.0.tar.bz2) and add some _optimization_.

**Todo**
- [x] ~Upgrade to version 13.0.0~
- [x] Upgrade to version 13.0.1
- [x] Enable ["Strict-Transport-Security"](https://docs.nextcloud.com/server/13/admin_manual/configuration_server/harden_server.html#enable-http-strict-transport-security) HTTP header
- [x] Add virtual host "nextcloud.\<DOMAIN\>"
- [x] Configure [PHP OPcache](https://docs.nextcloud.com/server/13/admin_manual/configuration_server/server_tuning.html#enable-php-opcache)
- [x] Enable [memcache](https://docs.nextcloud.com/server/13/admin_manual/configuration_server/server_tuning.html)~
- [x] Update PHP version
- [x] ~Test HTTP2 (it needs nginx)~

**Components**
[nethserver-nextcloud](https://github.com/nethserver/nethserver-nextcloud)
[server-packages](https://github.com/nextcloud/server-packages)
[nethserver-rh-php56-php-fpm](https://github.com/NethServer/nethserver-rh-php56-php-fpm)

**Comment by alepolidori** [comment]
**Note for:** *Enable "Strict-Transport-Security" HTTP header*

As exposed [here](https://docs.nextcloud.com/server/13/admin_manual/configuration_server/harden_server.html#enable-http-strict-transport-security)  `; preload` option can be added to apache config. Evaluate it.

**Comment by nethbot** [comment]
in `7.4.1708/testing`:
- [nethserver-rh-php71-php-fpm-1.0.0-1.3.g395a32c.ns7.noarch.rpm](http://packages.nethserver.org/nethserver/7.4.1708/testing/x86_64/Packages/nethserver-rh-php71-php-fpm-1.0.0-1.3.g395a32c.ns7.noarch.rpm)

**Comment by nethbot** [comment]
in `7.4.1708/testing`:
- [nethserver-nextcloud-1.1.11-1.8.g8f9047b.ns7.noarch.rpm](http://packages.nethserver.org/nethserver/7.4.1708/testing/x86_64/Packages/nethserver-nextcloud-1.1.11-1.8.g8f9047b.ns7.noarch.rpm)

**Comment by alepolidori** [comment]
How to test

1. test clean install and update from 12.0.5
1. verify that admin settings has no warnings or errors
1. verify login as admin and normal user with ldap and ad
1. verify one nextcloud app installation at least

**Comment by nethbot** [comment]
in `7.4.1708/testing`:
- [nethserver-nextcloud-1.1.11-1.10.gf5d7022.ns7.noarch.rpm](http://packages.nethserver.org/nethserver/7.4.1708/testing/x86_64/Packages/nethserver-nextcloud-1.1.11-1.10.gf5d7022.ns7.noarch.rpm)

**Comment by gsanchietti** [comment]
Verified both for Nextcloud 13.0.0 and 13.0.1

**Comment by nethbot** [comment]
in `7.4.1708/updates`:
- [nethserver-rh-php71-php-fpm-1.0.0-1.ns7.noarch.rpm](http://packages.nethserver.org/nethserver/7.4.1708/updates/x86_64/Packages/nethserver-rh-php71-php-fpm-1.0.0-1.ns7.noarch.rpm)

**Comment by nethbot** [comment]
in `7.4.1708/updates`:
- [nethserver-nextcloud-1.2.0-1.ns7.noarch.rpm](http://packages.nethserver.org/nethserver/7.4.1708/updates/x86_64/Packages/nethserver-nextcloud-1.2.0-1.ns7.noarch.rpm)
