### ISSUE TITLE
Upgrade tool beta2 

### ISSUE THREAD

**Issue by DavidePrincipi** [NethServer/dev#5640]
Enhancements

- [x] collect "firmware" fact (and backport to ns6)

In-place upgrade issues:
- [x] Ntopng fails to start after upgrade: http://dev.nethserver.org/issues/3450
- [x] IPsec daemon blocked after upgrade: http://dev.nethserver.org/issues/3449
- [x] Web filter uneffective after upgrade: http://dev.nethserver.org/issues/3448
- [x] Backport of logical interface integrity checks: http://dev.nethserver.org/issues/3447 (#5331 #5637)

In-place upgrade docs:
- [x] How to fix: Let's Encrypt certificate
- [x] ownCloud/NextCloud migration path notes
- [x] Note: refresh browser cache after upgrade
- [x] Upgrade to AD notes

**See also**

https://community.nethserver.org/t/upgrade-tool-module/11112

**Comment by nethbot** [comment]
in `7.5.1804/testing`:
- [nethserver-subscription-3.1.2-1.1.g12641e8.ns7.noarch.rpm](http://packages.nethserver.org/nethserver/7.5.1804/testing/x86_64/Packages/nethserver-subscription-3.1.2-1.1.g12641e8.ns7.noarch.rpm)
- [nethserver-subscription-ui-3.1.2-1.1.g12641e8.ns7.noarch.rpm](http://packages.nethserver.org/nethserver/7.5.1804/testing/x86_64/Packages/nethserver-subscription-ui-3.1.2-1.1.g12641e8.ns7.noarch.rpm)

**Comment by DavidePrincipi** [comment]
In nethesis-updates:
- nethserver-inventory-1.0.8-1.ns6.noarch.rpm

**Comment by DavidePrincipi** [comment]
In nethserver-testing 6.10:

- nethserver-upgrade-tool-1.0.0-1.11.gbc26615.ns6.x86_64.rpm

**Comment by DavidePrincipi** [comment]
In nethserver-updates 6.10:
- nethserver-upgrade-tool-1.1.0-1.ns6.x86_64.rpm
- nethserver-base-2.11.5-1.ns6.noarch.rpm
- nethserver-dnsmasq-1.5.7-1.ns6.noarch.rpm
- nethserver-firewall-base-2.11.6-1.ns6.noarch.rpm
- nethserver-firewall-base-ui-2.11.6-1.ns6.noarch.rpm

**Comment by DavidePrincipi** [comment]
In nethesis-updates 6.10:
- nethserver-register-2.3.1-1.ns6.noarch.rpm
