### ISSUE TITLE
NS 7.9.2009 rollout task list

### ISSUE THREAD

**Issue by DavidePrincipi** [NethServer/dev#6330]
- [x] Push nethserver-release for 7.9.2009
- [x] Feature Freeze - Send TravisCI.com builds to 7.9
- [x] Hide port 980 in first time /etc/issue by Anaconda
- [x] Update link to [release rpm](http://mirror.nethserver.org/nethserver/nethserver-release-7.rpm)
- [x] Serve 7.8.2003 from vault
- [x] Close ISO packages set issues
- [x] Test ns6 upgrade procedure
- [x] Release ISO 7.9.2009
- [x] Docs: merge release notes
- [x] GA announcement - switch mirrorlist stable repo to 7.9.2009
- [x] Release nethserver-subscription in 7.8.2003 to start NS 7.9 rollout

**Comment by nethbot** [comment]
in `7.9.2009/testing`:
- nethserver-createiso-1.7.0-1.1.gb5c7c07.ns7.noarch.rpm [x86_64](http://packages.nethserver.org/nethserver/7.9.2009/testing/x86_64/Packages/nethserver-createiso-1.7.0-1.1.gb5c7c07.ns7.noarch.rpm) [armhfp](http://packages.nethserver.org/nethserver/7.9.2009/testing/armhfp/Packages/nethserver-createiso-1.7.0-1.1.gb5c7c07.ns7.noarch.rpm) [aarch64](http://packages.nethserver.org/nethserver/7.9.2009/testing/aarch64/Packages/nethserver-createiso-1.7.0-1.1.gb5c7c07.ns7.noarch.rpm)

**Comment by nethbot** [comment]
in `7.9.2009/testing`:
- nethserver-createiso-1.7.0-1.5.g4aef6ce.ns7.noarch.rpm [x86_64](http://packages.nethserver.org/nethserver/7.9.2009/testing/x86_64/Packages/nethserver-createiso-1.7.0-1.5.g4aef6ce.ns7.noarch.rpm) [armhfp](http://packages.nethserver.org/nethserver/7.9.2009/testing/armhfp/Packages/nethserver-createiso-1.7.0-1.5.g4aef6ce.ns7.noarch.rpm) [aarch64](http://packages.nethserver.org/nethserver/7.9.2009/testing/aarch64/Packages/nethserver-createiso-1.7.0-1.5.g4aef6ce.ns7.noarch.rpm)

**Comment by nethbot** [comment]
in `7.9.2009/updates`:
- nethserver-createiso-1.7.1-1.ns7.noarch.rpm [x86_64](http://packages.nethserver.org/nethserver/7.9.2009/updates/x86_64/Packages/nethserver-createiso-1.7.1-1.ns7.noarch.rpm) [armhfp](http://packages.nethserver.org/nethserver/7.9.2009/updates/armhfp/Packages/nethserver-createiso-1.7.1-1.ns7.noarch.rpm) [aarch64](http://packages.nethserver.org/nethserver/7.9.2009/updates/aarch64/Packages/nethserver-createiso-1.7.1-1.ns7.noarch.rpm)

**Comment by nethbot** [comment]
in `7.9.2009/testing`:
- nethserver-subscription-inventory-3.6.5-1.1.ga5f88b6.ns7.x86_64.rpm [x86_64](http://packages.nethserver.org/nethserver/7.9.2009/testing/x86_64/Packages/nethserver-subscription-inventory-3.6.5-1.1.ga5f88b6.ns7.x86_64.rpm)

**Comment by nethbot** [comment]
in `7.9.2009/testing`:
- nethserver-subscription-3.6.5-1.1.ga5f88b6.ns7.noarch.rpm [x86_64](http://packages.nethserver.org/nethserver/7.9.2009/testing/x86_64/Packages/nethserver-subscription-3.6.5-1.1.ga5f88b6.ns7.noarch.rpm) [armhfp](http://packages.nethserver.org/nethserver/7.9.2009/testing/armhfp/Packages/nethserver-subscription-3.6.5-1.1.ga5f88b6.ns7.noarch.rpm) [aarch64](http://packages.nethserver.org/nethserver/7.9.2009/testing/aarch64/Packages/nethserver-subscription-3.6.5-1.1.ga5f88b6.ns7.noarch.rpm) 
- nethserver-subscription-ui-3.6.5-1.1.ga5f88b6.ns7.noarch.rpm [x86_64](http://packages.nethserver.org/nethserver/7.9.2009/testing/x86_64/Packages/nethserver-subscription-ui-3.6.5-1.1.ga5f88b6.ns7.noarch.rpm) [armhfp](http://packages.nethserver.org/nethserver/7.9.2009/testing/armhfp/Packages/nethserver-subscription-ui-3.6.5-1.1.ga5f88b6.ns7.noarch.rpm) [aarch64](http://packages.nethserver.org/nethserver/7.9.2009/testing/aarch64/Packages/nethserver-subscription-ui-3.6.5-1.1.ga5f88b6.ns7.noarch.rpm)

**Comment by nethbot** [comment]
in `7.9.2009/updates`:
- nethserver-subscription-inventory-3.6.6-1.ns7.x86_64.rpm [x86_64](http://packages.nethserver.org/nethserver/7.9.2009/updates/x86_64/Packages/nethserver-subscription-inventory-3.6.6-1.ns7.x86_64.rpm)

**Comment by nethbot** [comment]
in `7.9.2009/updates`:
- nethserver-subscription-3.6.6-1.ns7.noarch.rpm [x86_64](http://packages.nethserver.org/nethserver/7.9.2009/updates/x86_64/Packages/nethserver-subscription-3.6.6-1.ns7.noarch.rpm) [armhfp](http://packages.nethserver.org/nethserver/7.9.2009/updates/armhfp/Packages/nethserver-subscription-3.6.6-1.ns7.noarch.rpm) [aarch64](http://packages.nethserver.org/nethserver/7.9.2009/updates/aarch64/Packages/nethserver-subscription-3.6.6-1.ns7.noarch.rpm) 
- nethserver-subscription-ui-3.6.6-1.ns7.noarch.rpm [x86_64](http://packages.nethserver.org/nethserver/7.9.2009/updates/x86_64/Packages/nethserver-subscription-ui-3.6.6-1.ns7.noarch.rpm) [armhfp](http://packages.nethserver.org/nethserver/7.9.2009/updates/armhfp/Packages/nethserver-subscription-ui-3.6.6-1.ns7.noarch.rpm) [aarch64](http://packages.nethserver.org/nethserver/7.9.2009/updates/aarch64/Packages/nethserver-subscription-ui-3.6.6-1.ns7.noarch.rpm)
